import pytest
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
from chispa.dataframe_comparer import assert_df_equality

NOTEBOOK_PATH = "databricks/notebooks/bronze/Initial_Load_Dynamic.py"

@pytest.fixture
def setup_initial_staging(spark, tmp_path):
    """Creates synthetic staging data for the initial load."""
    schema = StructType([
        StructField("CUSTOMER_ID", IntegerType(), True),
        StructField("NAME", StringType(), True),
        StructField("EMAIL", StringType(), True)
    ])
    
    # Includes valid rows and a row with a null PK (Data Quality check)
    data = [
        (1, "Alice", "alice@test.com"),
        (2, "Bob", "bob@test.com"),
        (None, "Unknown", "unknown@test.com") # Engineered bad row
    ]
    
    df = spark.createDataFrame(data, schema)
    
    # Match the path structure generated by the notebook
    staging_dir = f"{tmp_path}/bronze/staging/src-002/crm/customers/initial/run-123/"
    df.write.mode("overwrite").parquet(staging_dir)
    return staging_dir

@pytest.mark.integration
@pytest.mark.idempotency
def test_initial_load_idempotency_and_contract(spark, run_notebook, setup_initial_staging, tmp_path):
    """
    Tests Initial Load:
    1. Contract: Metadata columns are added correctly.
    2. Reconciliation: Row counts match.
    3. Idempotency: Running twice overwrites the partition, no duplicates.
    """
    widgets = {
        "pipeline_run_id": "run-123",
        "table_id": "1",
        "source_system": "src-002",
        "schema_name": "crm",
        "table_name": "customers",
        "primary_key_columns": "CUSTOMER_ID"
    }
    
    # --- FIRST RUN ---
    result1 = run_notebook(NOTEBOOK_PATH, widgets)
    
    assert result1["status"] == "SUCCESS"
    assert result1["records_loaded"] == 3
    
    delta_path = f"{tmp_path}/bronze/src-002/crm/customers/"
    df_first_run = spark.read.format("delta").load(delta_path)
    
    # Contract Check: Ensure metadata columns exist
    expected_columns = {"CUSTOMER_ID", "NAME", "EMAIL", "_pipeline_run_id", 
                        "_ingest_timestamp", "_source_system", "_cdc_operation", "ingest_date"}
    assert set(df_first_run.columns) == expected_columns
    assert df_first_run.count() == 3
    
    # --- SECOND RUN (IDEMPOTENCY) ---
    result2 = run_notebook(NOTEBOOK_PATH, widgets)
    assert result2["status"] == "SUCCESS"
    
    df_second_run = spark.read.format("delta").load(delta_path)
    
    # Reconciliation & Idempotency: Count should still be 3, data should be identical
    assert df_second_run.count() == 3
    
    # Drop ingest_timestamp for equality check since it changes on re-run
    df1_cmp = df_first_run.drop("_ingest_timestamp")
    df2_cmp = df_second_run.drop("_ingest_timestamp")
    
    assert_df_equality(df1_cmp, df2_cmp, ignore_row_order=True)