# Example backend configuration. 
# Replace 'storage_account_name' with the actual name generated by bootstrap.sh
resource_group_name  = "rg-terraform-state-core"
storage_account_name = "sttfstatecore123456"
container_name       = "tfstate"
key                  = "data-platform.tfstate"